/* nosmaps static UI mock — shared records are loaded from data.js. */
const {categories,purposes,statuses,statusJa,tools}=window.NOSMAPS_DATA;
const state={screen:'home',mode:'A',query:'',category:'all',status:'all',platform:'all',purpose:'',compare:[],uiState:'normal',sort:'name'};
const main=document.querySelector('#main');
const detailDialog=document.querySelector('#detail-dialog');
const contributionDialog=document.querySelector('#contribute-dialog');

function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function statusBadge(t){return `<span class="status ${t.status}">${statusJa[t.status]}</span>`}
function routeHash(){history.replaceState(null,'',state.screen==='home'?'#home':`#concept-${state.mode.toLowerCase()}`)}
function renderHome(){state.screen='home';routeHash();main.innerHTML=`
  <section class="hero"><div class="eyebrow">Static prototype · 36 shared mock records</div><h1>Nostrの道具を、<br>どう見つけたい？</h1><p class="lead">同じ架空データを使った4つのUI案です。情報設計ではなく、まず触って比較するためのモック。</p><p class="mock-note">⚠ すべての状態・観測値はモック。Nostr未接続・送信なし。</p></section>
  <section class="compare-prompt"><strong>何を比較してほしいか</strong><br>① 初見で次の操作が分かるか　② 欲しいツールへ早く着けるか　③ 状態の根拠を信頼できそうか　④ また探索したくなるか</section>
  <section class="concept-grid" aria-label="UI案を選ぶ">
    ${conceptCard('A','目的から探す','初心者・Nostrを始めたばかりの人','やりたいことを言葉で選べば、用語を知らなくても候補に着ける。',['目的カードから開始','おすすめ順の短いリスト','次の一歩を明示'])}
    ${conceptCard('B','一覧・絞り込み・比較','候補を効率よく評価したい人','高密度な一覧と2〜3件比較で、判断に必要な差分を早く掴める。',['複数条件で絞り込み','最大3件を横比較','観測根拠を一覧で確認'])}
    ${conceptCard('C','カテゴリを辿る探索','周辺領域も含めて発見したい人','分類を歩くことで、検索語を決めずに意外な道具と出会える。',['カテゴリツリー','関連領域への寄り道','発見を促すカード'])}
    <article class="concept-card concept-card-d"><span class="letter">D</span><h2>NIP探索・比較</h2><p><strong>対象：</strong>既存Nostr利用者・開発者</p><p>NIPを起点に架空ツールを逆引きし、対応状況と根拠を比較する。</p><ul><li>NIP番号・名称・用途検索</li><li>対応ツールの逆引き</li><li>最大3件のNIPマトリクス</li></ul><a class="primary link-button" href="nip-explorer.html">D案を操作する</a></article>
  </section>
  <section class="principles"><div class="principle"><strong>同じ36件</strong><br><span>全案で共通の架空データ。</span></div><div class="principle"><strong>根拠を隠さない</strong><br><span>状態と観測日時を詳細・比較に表示。</span></div><div class="principle"><strong>静的で完結</strong><br><span>バックエンド・API・DB・中央インデクサなし。</span></div></section>`;}
function conceptCard(letter,title,user,hypothesis,points){return `<article class="concept-card"><span class="letter">${letter}</span><h2>${title}</h2><p><strong>対象：</strong>${user}</p><p>${hypothesis}</p><ul>${points.map(x=>`<li>${x}</li>`).join('')}</ul><button class="primary" data-action="open-mode" data-mode="${letter}">${letter}案を操作する</button></article>`}
function filtered(){let list=tools.filter(t=>(state.category==='all'||t.category===state.category)&&(state.status==='all'||t.status===state.status)&&(state.platform==='all'||t.platform===state.platform)&&(!state.purpose||t.purposes.includes(state.purpose))&&(!state.query||`${t.name} ${t.description} ${t.tags.join(' ')}`.toLowerCase().includes(state.query.toLowerCase())));if(state.sort==='status')list.sort((a,b)=>statuses.indexOf(a.status)-statuses.indexOf(b.status));else list.sort((a,b)=>a.name.localeCompare(b.name));return list;}
function renderApp(){state.screen='app';routeHash();const meta={A:['目的から探す','対象：初心者。やりたいことから選べば、用語を知らなくても候補へ着ける。'],B:['一覧・絞り込み・比較','対象：比較検討する人。密度の高い一覧と最大3件比較で、差分を速く掴む。'],C:['カテゴリを辿る探索','対象：探索したい人。分類を歩き、検索語なしでも周辺の道具と出会う。']}[state.mode];main.innerHTML=`
  <header class="app-head"><div><div class="eyebrow">CONCEPT ${state.mode}</div><h1>${meta[0]}</h1><p class="hypothesis">${meta[1]}</p></div><div class="mode-switch" aria-label="案を切り替える">${['A','B','C'].map(x=>`<button data-action="open-mode" data-mode="${x}" aria-current="${state.mode===x}">${x}</button>`).join('')}</div></header>
  ${state.mode==='A'?purposePanel():''}${state.mode==='C'?categoryView():standardView()}
  ${stateLab()}<p class="footer-note">この画面の名称、状態、観測値はすべてUI確認用のモックです。実在サービスの稼働状況を示しません。</p>`;renderCompareDock();}
function purposePanel(){return `<section class="purpose-panel"><h2>今日は何をしたい？</h2><p>専門用語はあとで大丈夫。近いものをひとつ選んでください。</p><div class="purpose-grid">${purposes.map(p=>`<button class="chip ${state.purpose===p?'selected':''}" data-action="purpose" data-purpose="${p}">${p}</button>`).join('')}<button class="chip ${!state.purpose?'selected':''}" data-action="purpose" data-purpose="">全部見る</button></div></section>`}
function toolbar(){return `<section class="toolbar" aria-label="検索と絞り込み"><div class="field"><label for="search">キーワード検索</label><input id="search" type="search" value="${esc(state.query)}" placeholder="名前・特徴で検索"></div><div class="field"><label for="category">カテゴリ</label><select id="category"><option value="all">すべて</option>${categories.map(c=>`<option value="${c[0]}" ${state.category===c[0]?'selected':''}>${c[1]}</option>`).join('')}</select></div><div class="field"><label for="status">状態</label><select id="status"><option value="all">すべて</option>${statuses.map(s=>`<option value="${s}" ${state.status===s?'selected':''}>${s}</option>`).join('')}</select></div><div class="field"><label for="platform">環境</label><select id="platform"><option value="all">すべて</option>${['Web','Desktop','Mobile'].map(p=>`<option ${state.platform===p?'selected':''}>${p}</option>`).join('')}</select></div></section>`}
function standardView(){const list=filtered();return `${toolbar()}<div class="results-meta"><strong>${list.length}件のモック候補</strong><label>並び順 <select id="sort"><option value="name" ${state.sort==='name'?'selected':''}>名前</option><option value="status" ${state.sort==='status'?'selected':''}>状態</option></select></label></div>${results(list)}`}
function categoryView(){const list=filtered();return `<div class="category-layout"><aside class="category-tree" aria-label="カテゴリ"><button class="ghost ${state.category==='all'?'selected':''}" data-action="category" data-category="all">🗺️ すべて</button>${categories.map(c=>`<button class="ghost ${state.category===c[0]?'selected':''}" data-action="category" data-category="${c[0]}">${c[2]} ${c[1]} <small>6</small></button>`).join('')}</aside><section><div class="breadcrumb"><button class="ghost" data-action="category" data-category="all">全領域</button><span>›</span><strong>${state.category==='all'?'発見フィード':categories.find(c=>c[0]===state.category)[1]}</strong></div>${toolbar()}<div class="results-meta"><strong>${list.length}件を探索中</strong><span>隣のカテゴリにも寄り道できます</span></div>${results(list)}</section></div>`}
function results(list){if(state.uiState==='loading')return `<div class="skeleton" aria-label="読み込み中"><span></span><span></span><span></span></div>`;if(state.uiState==='empty'||!list.length)return `<div class="empty"><h2>候補が見つかりません</h2><p>条件を減らすか、別の言葉で試してください。</p><button class="secondary" data-action="reset">条件をリセット</button></div>`;if(state.uiState==='error')return `<div class="empty"><h2>表示を再現できませんでした</h2><p>エラー状態のUIモックです。データは失われていません。</p><button class="primary" data-action="ui-state" data-state="normal">もう一度試す</button></div>`;let show=list;if(state.uiState==='partial')show=list.slice(0,7);return `${state.uiState==='partial'?'<div class="partial-note" role="status"><strong>一部のみ表示：</strong>36件中、保存済みの7件を確認できました（モック）。</div>':''}<div class="results">${show.map(toolCard).join('')}</div>`}
function toolCard(t){const checked=state.compare.includes(t.id);return `<article class="tool-card"><div class="card-top"><span class="tool-icon" aria-hidden="true">${t.icon}</span>${statusBadge(t)}</div><h3>${t.name}</h3><p>${t.description}</p><div class="tags">${t.tags.map(x=>`<span class="tag">${x}</span>`).join('')}</div><p class="status-line"><span>${t.platform}</span><small>観測 ${t.observed.split(' ')[0]}</small></p><div class="card-actions"><button class="secondary" data-action="detail" data-id="${t.id}">詳細を見る</button><label class="compare-check"><input type="checkbox" data-action="compare" data-id="${t.id}" ${checked?'checked':''}> 比較</label></div></article>`}
function renderCompareDock(){document.querySelector('.compare-dock')?.remove();if(!state.compare.length)return;const el=document.createElement('div');el.className='compare-dock';el.innerHTML=`<span><strong>${state.compare.length}件を選択</strong> <small>（2〜3件推奨）</small></span><button class="primary" data-action="show-compare" ${state.compare.length<2?'disabled':''}>比較する</button><button class="ghost danger" data-action="clear-compare">解除</button>`;document.body.append(el)}
function showDetail(id){const t=tools.find(x=>x.id===id);detailDialog.querySelector('#detail-content').innerHTML=`<div class="dialog-head"><div><div class="eyebrow">${t.categoryLabel} · MOCK RECORD</div><h2 id="detail-title">${t.icon} ${t.name}</h2></div><button class="icon-btn" data-action="close-detail" aria-label="閉じる">✕</button></div><p>${t.description}</p><p>${statusBadge(t)} <strong>${t.basis}</strong></p><section class="evidence"><div><span class="label">最終観測日時</span><br><strong>${t.observed}</strong></div><div><span class="label">判定方法</span><br>静的モックルール v0</div><div><span class="label">対応環境</span><br>${t.platform}</div><div><span class="label">ライセンス</span><br>${t.license}</div></section><h3>観測ログ（すべてモック）</h3><ul class="timeline">${t.observations.map(x=>`<li>${x}</li>`).join('')}</ul><div class="mock-note">実在サービスへの疎通結果ではありません</div><div class="card-actions"><button class="primary" data-action="add-and-compare" data-id="${t.id}">比較候補に追加</button><button class="secondary" data-action="open-correction" data-id="${t.id}">作者として訂正案</button></div>`;detailDialog.showModal();}
function showCompare(){const selected=state.compare.map(id=>tools.find(t=>t.id===id));detailDialog.querySelector('#detail-content').innerHTML=`<div class="dialog-head"><div><div class="eyebrow">COMPARE · MOCK</div><h2 id="detail-title">${selected.length}件を比較</h2></div><button class="icon-btn" data-action="close-detail" aria-label="閉じる">✕</button></div><div class="compare-table"><table><thead><tr><th>項目</th>${selected.map(t=>`<th>${t.name}</th>`).join('')}</tr></thead><tbody><tr><th>状態</th>${selected.map(t=>`<td>${statusBadge(t)}</td>`).join('')}</tr><tr><th>根拠</th>${selected.map(t=>`<td>${t.basis}</td>`).join('')}</tr><tr><th>観測日時</th>${selected.map(t=>`<td>${t.observed}</td>`).join('')}</tr><tr><th>カテゴリ</th>${selected.map(t=>`<td>${t.categoryLabel}</td>`).join('')}</tr><tr><th>環境</th>${selected.map(t=>`<td>${t.platform}</td>`).join('')}</tr><tr><th>ライセンス</th>${selected.map(t=>`<td>${t.license}</td>`).join('')}</tr></tbody></table></div><p class="mock-note">状態・根拠・日時を含む全項目がモックです</p>`;detailDialog.showModal();}
function stateLab(){return `<section class="state-lab"><div class="section-head"><div><span class="eyebrow">UI STATE LAB</span><h2>主要状態を確認</h2></div></div><div class="state-buttons">${['normal','loading','empty','error','partial','offline'].map(s=>`<button class="secondary" data-action="ui-state" data-state="${s}" aria-pressed="${state.uiState===s}">${s}</button>`).join('')}</div><div class="state-view"><p><strong>現在：${state.uiState}</strong><br>${{normal:'通常の操作状態',loading:'読み込み中のスケルトン',empty:'検索結果なし',error:'再試行できるエラー',partial:'一部データだけ取得',offline:'オフラインで保存済みデータを表示'}[state.uiState]}</p></div></section>`}
function openContribution(kind,toolId=''){const map={submit:['候補を投稿','新しい道具の候補'],curate:['キュレーション','掲載候補への推薦コメント'],correction:['作者訂正','作者からの修正提案']};const [title,desc]=map[kind];const tool=tools.find(t=>t.id===toolId);contributionDialog.querySelector('#contribute-content').innerHTML=`<div class="dialog-head"><div><div class="eyebrow">NOSTR NOT CONNECTED</div><h2 id="contribute-title">${title}</h2><p>${desc}を作る操作イメージです。</p></div><button class="icon-btn" data-action="close-contribute" aria-label="閉じる">✕</button></div><form id="contribution-form" data-kind="${kind}"><div class="form-grid"><div class="field"><label for="con-name">対象名</label><input id="con-name" required value="${tool?tool.name:''}" placeholder="例：新しいツール"></div><div class="field"><label for="con-category">カテゴリ</label><select id="con-category">${categories.map(c=>`<option>${c[1]}</option>`).join('')}</select></div><div class="field full"><label for="con-note">提案内容</label><textarea id="con-note" rows="4" required placeholder="確認してほしい内容、根拠など"></textarea></div><div class="field full"><label><input id="con-author" type="checkbox" style="width:auto"> 作者として提案する（このモックでは本人確認なし）</label></div></div><h3>イベントプレビュー</h3><div class="preview" id="event-preview"><code>{ kind: "未接続", content: "入力するとプレビュー" }</code></div><p class="form-status"><strong>状態：下書きのみ</strong><br>秘密鍵へのアクセス、署名、リレー送信は一切行いません。</p><button class="primary" type="submit">送信直前の状態を確認</button></form>`;contributionDialog.showModal();}
function toast(msg){const e=document.querySelector('#toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}

document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='home')renderHome();if(a==='open-mode'){state.mode=b.dataset.mode;state.category='all';state.purpose='';state.uiState='normal';renderApp()}if(a==='purpose'){state.purpose=b.dataset.purpose;renderApp()}if(a==='category'){state.category=b.dataset.category;renderApp()}if(a==='detail')showDetail(b.dataset.id);if(a==='close-detail')detailDialog.close();if(a==='close-contribute')contributionDialog.close();if(a==='open-submit')openContribution('submit');if(a==='open-curate')openContribution('curate');if(a==='open-correction')openContribution('correction',b.dataset.id);if(a==='add-and-compare'){if(!state.compare.includes(b.dataset.id)&&state.compare.length<3)state.compare.push(b.dataset.id);detailDialog.close();renderApp();toast('比較候補に追加しました')}if(a==='show-compare')showCompare();if(a==='clear-compare'){state.compare=[];renderCompareDock()}if(a==='reset'){state.query='';state.category='all';state.status='all';state.platform='all';state.purpose='';state.uiState='normal';renderApp()}if(a==='ui-state'){state.uiState=b.dataset.state;document.querySelector('#offline-banner').hidden=state.uiState!=='offline';renderApp()} });
document.addEventListener('change',e=>{if(e.target.matches('[data-action="compare"]')){const id=e.target.dataset.id;if(e.target.checked){if(state.compare.length>=3){e.target.checked=false;toast('比較は最大3件です');return}state.compare.push(id)}else state.compare=state.compare.filter(x=>x!==id);renderCompareDock()}if(e.target.id==='category'){state.category=e.target.value;renderApp()}if(e.target.id==='status'){state.status=e.target.value;renderApp()}if(e.target.id==='platform'){state.platform=e.target.value;renderApp()}if(e.target.id==='sort'){state.sort=e.target.value;renderApp()}});
document.addEventListener('input',e=>{if(e.target.id==='search'){state.query=e.target.value;renderApp();const s=document.querySelector('#search');s.focus();s.setSelectionRange(state.query.length,state.query.length)}if(e.target.id==='con-note'||e.target.id==='con-name'){const n=document.querySelector('#con-name')?.value||'';const note=document.querySelector('#con-note')?.value||'';document.querySelector('#event-preview').innerHTML=`<code>{ kind: "Nostr未接続", name: "${esc(n)}", content: "${esc(note)}" }</code>`}});
document.addEventListener('submit',e=>{if(e.target.id==='contribution-form'){e.preventDefault();e.target.querySelector('.form-status').innerHTML='<strong>状態：プレビュー確認済み（未送信）</strong><br>署名・送信ボタンは意図的に実装していません。';toast('未送信のプレビューを更新しました')}});
window.addEventListener('hashchange',()=>{if(location.hash==='#home')renderHome()});
renderHome();
