/* Ambient types for the classic-script globals the pages hang their data off.
   Nothing here is imported; every page loads these files with a plain <script>
   tag and reads them back off `window`, so the only place their shape can be
   stated is a global declaration.

   The catalogue types below are derived from the 41 real entries in data.js as
   generated by tools/build-data.mjs — every field was read out of the data, and
   a field that is absent or null for some entries is typed as optional or as an
   explicit null, never widened to `string` or `any`. Counts quoted in comments
   are the measured counts over data.js at the revision this file was written
   against (41 tools, 313 capability claims, 69 provenance sources, 9 liveness
   observations, 94 registry entries). */

/* ------------------------------------------------------------------------ */
/* data.js — window.NOSMAPS_DATA                                             */
/* ------------------------------------------------------------------------ */

/** §19.1: the pinned NIP registry snapshot. `number` is the opaque ASCII token
    ("01", "5A"), never an integer — all 94 entries are strings. */
interface NosmapsNipRegistryEntry {
  readonly number: string;
  readonly title: string;
  readonly deprecated: boolean;
  /** "" for an entry the registry does not annotate; the empty string is the
      absent form, and 94/94 entries carry the key. */
  readonly note: string;
  readonly source: string;
}

/** §21.2 R2: bud/lud are first-class families alongside nip. All three occur in
    the collected claims. */
type NosmapsCapabilityFamily = 'nip' | 'bud' | 'lud';

/** §21.7 R7: the seven stated results, matching data.resultPrecedence exactly.
    `unknown` is deliberately NOT one of them — it is what the UI shows when no
    stated result exists, so it never appears in the data. */
type NosmapsCapabilityResult =
  | 'supported'
  | 'partial'
  | 'disabled'
  | 'planned'
  | 'withdrawn'
  | 'not_supported'
  | 'not_applicable';

/** §21.2.3: the result of matching the claim's id against the pinned snapshot. */
type NosmapsRegistryStatus = 'resolved' | 'not_in_registry' | 'unresolvable';

/** §21.1 R1. The i18n dictionary carries three basis labels (transcribed /
    self_declared / tested), but the collector emits only `transcribed`, and all
    313 collected claims carry it. Typed as what the data holds. */
type NosmapsClaimBasis = 'transcribed';

/** A single capability claim: the family, the verbatim source line, and the
    status the id resolves to against the pinned snapshot. */
interface NosmapsCapabilityClaim {
  readonly family: NosmapsCapabilityFamily;
  /** Opaque token, so "5A" indexes exactly like "01". */
  readonly id: string;
  /** The `/sub` token of family:id[/sub][@scope]. Null in all 313 collected
      claims — no primary source used a sub-token — so null is its observed
      state, not a placeholder. */
  readonly sub: null;
  /** The `@scope` token. Null for 309 of 313; the four that carry one are
      "android" and "commonmain". */
  readonly scope: string | null;
  /** The reassembled key, family:id[/sub][@scope]. */
  readonly key: string;
  readonly result: NosmapsCapabilityResult;
  /** The claim exactly as the primary source wrote it. */
  readonly sourceText: string;
  /** The qualification the source attached, verbatim. Null for 283 of 313. */
  readonly caveat: string | null;
  readonly registryStatus: NosmapsRegistryStatus;
  /** The snapshot's title for this id. Null for the 22 claims whose id the
      snapshot does not hold or whose family it does not cover. */
  readonly registryTitle: string | null;
  readonly deprecated: boolean;
  readonly basis: NosmapsClaimBasis;
  /** The document the claim was transcribed from. */
  readonly source: string;
  readonly assertedAt: string;
}

/** §21.4 R4: liveness is an observation with a method, never a state. */
type NosmapsLivenessResult =
  | 'reachable'
  | 'unreachable'
  | 'archived'
  | 'moved'
  | 'superseded';

type NosmapsLivenessMethod = 'repository-metadata' | 'dns' | 'http';

interface NosmapsLivenessObservation {
  readonly result: NosmapsLivenessResult;
  readonly method: NosmapsLivenessMethod;
  readonly detail: string;
  /** Where the subject moved/was superseded to. Genuinely absent — the key is
      not present at all — on 5 of the 9 observations, so it is optional rather
      than nullable. */
  readonly target?: string;
  readonly subject: string;
  readonly observedAt: string;
}

/** Names the primary source is quoted for. */
type NosmapsSourceField = 'name' | 'summary' | 'homepage';

interface NosmapsProvenanceSource {
  readonly fields: readonly NosmapsSourceField[];
  readonly url: string;
  /** What was read at that URL, verbatim. */
  readonly what: string;
  readonly fetched: string;
}

/** A listing the source made that is explicitly NOT a support claim (modules or
    crates merely named after NIPs). Two occur across the 41 entries. */
interface NosmapsNonClaim {
  readonly kind: 'modules' | 'crates';
  readonly values: readonly string[];
}

/** The document the capability claims were transcribed from, and how it wrote
    them. */
interface NosmapsToolClaim {
  readonly source: string;
  readonly sourceLabel: string;
  /** How the source notated NIP references. Null for 19 of 41 — those sources
      state no NIPs at all, so there is no notation to record. */
  readonly notation: string | null;
  readonly fetched: string;
  /** Qualifications quoted from the source verbatim. */
  readonly caveats: readonly string[];
  readonly nonClaims: readonly NosmapsNonClaim[];
}

/** §21.4 R4: the record's own state, distinct from project liveness. The write
    path (nostr-catalog.js validateSoftwareEvent) accepts `active` and
    `withdrawn`; buildCatalog drops everything that is not `active`, so all 41
    collected entries are `active`. */
type NosmapsRecordState = 'active';

/** One catalogue entry. All 41 entries carry every key below — absence is
    expressed as null (or as "" for `summary`), never by omitting the key. */
interface NosmapsTool {
  /** The namespaced `d`, e.g. "nosmaps:io.damus". */
  readonly id: string;
  /** 30078:<publisher-hex>:<d>, with the publisher left as a template. */
  readonly coordinate: string;
  readonly name: string;
  /** §21.5 R5: "" is the normative absent form, paired with summaryAbsent. */
  readonly summary: string;
  readonly summaryAbsent: boolean;
  /** Null for 14 of 41 — those primary sources state no homepage. */
  readonly homepage: string | null;
  readonly recordState: NosmapsRecordState;
  /** §21.6 R6: seed topics plus free lowercase topics, rendered verbatim. Not
      restricted to seedTopics: the 41 entries use 11 distinct topics against 7
      seeds. */
  readonly topics: readonly string[];
  /** The topics as collected, before any correction. */
  readonly collectedTopics: readonly string[];
  /** Why `topics` differs from `collectedTopics`. Null for 33 of 41. */
  readonly topicCorrection: string | null;
  readonly provenance: 'collected';
  readonly observed: string;
  readonly sources: readonly NosmapsProvenanceSource[];
  readonly license: string;
  /** The platforms the primary source names, verbatim. Null for 39 of 41 —
      almost no source states one. */
  readonly platformText: string | null;
  /** How the project is distributed, verbatim. Null for 38 of 41. */
  readonly distribution: string | null;
  readonly sourceRepo: string;
  /** Empty for the 21 entries whose source claims no capabilities. */
  readonly capabilities: readonly NosmapsCapabilityClaim[];
  readonly claim: NosmapsToolClaim;
  /** Empty for the 35 entries with no recorded liveness observation. */
  readonly liveness: readonly NosmapsLivenessObservation[];
  /** Numbered findings from the collection report. */
  readonly findings: readonly number[];
}

interface NosmapsDataMeta {
  readonly collected: string;
  readonly collector: string;
  readonly entryCount: number;
  readonly notCollected: readonly {readonly name: string; readonly why: string}[];
}

interface NosmapsRegistryPin {
  readonly family: NosmapsCapabilityFamily;
  readonly registry: string;
  readonly revision: string;
  readonly source: string;
  readonly fetched: string;
}

interface NosmapsData {
  readonly meta: NosmapsDataMeta;
  /** §21.6 R6: the seven seed topics. */
  readonly seedTopics: readonly string[];
  /** Highest-precedence result first. */
  readonly resultPrecedence: readonly NosmapsCapabilityResult[];
  readonly registry: NosmapsRegistryPin;
  readonly nipCatalog: readonly NosmapsNipRegistryEntry[];
  readonly tools: readonly NosmapsTool[];
}

/* ------------------------------------------------------------------------ */
/* i18n.js — window.NOSMAPS_I18N                                            */
/* ------------------------------------------------------------------------ */

type NosmapsLanguage = 'ja' | 'en';

/** A node of the translation dictionaries: a leaf string, a tuple of strings
    (the feature entries), or a nested group. */
type NosmapsI18nNode =
  | string
  | readonly NosmapsI18nNode[]
  | {readonly [key: string]: NosmapsI18nNode};

interface NosmapsI18nMissing {
  readonly path: string;
  readonly language: string;
  readonly detail: string;
}

interface NosmapsI18n {
  readonly language: NosmapsLanguage;
  readonly dictionaries: {readonly [language: string]: NosmapsI18nNode};
  /** Every lookup that resolved to nothing, in order. */
  readonly missing: readonly NosmapsI18nMissing[];
  has(path: string, selectedLanguage?: NosmapsLanguage): boolean;
  /** The raw dictionary node, which is `undefined` when the key is missing in
      both the selected language and the ja fallback. */
  value(path: string, selectedLanguage?: NosmapsLanguage): NosmapsI18nNode | undefined;
  /** Always a string: the key path itself stands in for a missing or
      non-string key, so nothing ever renders as "undefined". */
  t(
    path: string,
    variables?: {readonly [key: string]: string | number} | undefined,
    selectedLanguage?: NosmapsLanguage
  ): string;
  set(next: string): void;
  onChange(listener: (language: NosmapsLanguage) => void): () => void;
  applyDocument(): void;
}

/* ------------------------------------------------------------------------ */
/* icons.js — window.NOSMAPS_ICONS                                          */
/* ------------------------------------------------------------------------ */

interface NosmapsIcons {
  /** Falls back to the `apps` glyph for an unknown name; never returns "". */
  svg(name: string, className?: string): string;
  readonly names: readonly string[];
}

/* ------------------------------------------------------------------------ */
/* nostr-canonical.js — window.NOSMAPS_CANONICAL                            */
/* ------------------------------------------------------------------------ */

/** strictParse never throws: it reports the reason instead. `value` is the
    parsed JSON, so it is `unknown` — nothing about the bytes proves a shape. */
interface NosmapsParseResult {
  readonly ok: boolean;
  readonly value?: unknown;
  readonly error?: string;
}

interface NosmapsCanonical {
  utf8Encode(value: string): Uint8Array;
  utf8ByteLength(value: string): number;
  bytesEqual(a: Uint8Array, b: Uint8Array): boolean;
  isLowercaseSha256Hex(value: unknown): boolean;
  sha256Hex(bytes: Uint8Array): Promise<string>;
  /** Takes the raw UTF-8 bytes, not a decoded string: the BOM and invalid-UTF-8
      rejections are only observable before decoding. */
  strictParse(bytes: Uint8Array): NosmapsParseResult;
  canonicalize(value: unknown): Uint8Array;
  isCanonicalBytes(bytes: Uint8Array, value: unknown): boolean;
}

/* ------------------------------------------------------------------------ */
/* nostr-catalog.js — window.NOSMAPS_CATALOG                                */
/* ------------------------------------------------------------------------ */

interface NosmapsCatalogPolicy {
  readonly SOFTWARE_KIND: number;
  readonly CURATION_KIND: number;
  readonly FOLLOW_KIND: number;
  readonly DELETION_KIND: number;
  readonly DEFAULT_RELAYS: readonly string[];
  readonly DISCOVERY_TOPICS: readonly string[];
  readonly CATALOG_STALE_AFTER_MS: number;
  readonly GRAPH_STALE_AFTER_MS: number;
  readonly MAX_FUTURE_SKEW_SEC: number;
  readonly MAX_FUTURE_HORIZON_SEC: number;
  readonly MAX_MIGRATION_DEPTH: number;
  readonly DISCOVERY_LIMIT_PER_RELAY: number;
  readonly MAX_DISCOVERY_PAGES_PER_RELAY: number;
  readonly MAX_DISCOVERY_RAW_EVENTS_PER_RELAY: number;
  readonly GRAPH_MAX_FOLLOWS: number;
  readonly GRAPH_MAX_SETS_PER_CURATOR: number;
  readonly GRAPH_TIER2_ENABLED: boolean;
  readonly MAX_FILTERS_PER_REQ: number;
  readonly MAX_SERIALIZED_REQ_BYTES_FALLBACK: number;
  readonly MAX_ARRAY_ITEMS_PER_FILTER: number;
  readonly CLEANUP_LIMIT: number;
  readonly REQ_TIMEOUT_MS: number;
}

/** A row of the relay-derived catalogue. Distinct from NosmapsTool: this is the
    live record as observed, not a collected entry. */
interface NosmapsRelayEntry {
  readonly coordinate: string;
  readonly publisher: string;
  readonly d: string;
  readonly state: 'active';
  readonly fields: {
    readonly name: string;
    readonly summary: string;
    readonly homepage: string | null;
  };
  readonly topics: readonly string[];
  readonly supersededBy: string | null;
  readonly eventId: string | null;
  readonly createdAt: number;
  /** Null when the viewer has no graph — unknown, never 0 (invariant I8). */
  readonly recommendations: number | null;
  readonly recommenders: readonly string[];
  readonly manualRecommendations: number | null;
  readonly manualRecommenders: readonly string[];
  readonly quarantinedNewer: unknown;
  readonly relays: readonly string[];
  /** Served from the derived cache rather than re-observed this round. */
  readonly stale: boolean;
}

type NosmapsCatalogStatus = 'fresh' | 'stale' | 'incomplete' | 'unavailable';

interface NosmapsRelayCoverage {
  readonly status: string;
  readonly observedAt: number;
}

interface NosmapsGraphState {
  readonly state: string;
  readonly pubkeys: readonly string[];
  readonly coverage: string;
  readonly followsUsed: number;
  readonly followsTotal: number;
  readonly truncated: boolean;
  readonly malformedPTags: number;
  readonly viewerPubkey: string | null;
}

interface NosmapsRequestStats {
  readonly logicalReqs: number;
  readonly physicalReqs: number;
  /** §9.2: zero by construction — nothing in the catalog data path does HTTP. */
  readonly httpAttempts: number;
  readonly cacheHits: number;
}

interface NosmapsCatalogResult {
  readonly status: NosmapsCatalogStatus;
  readonly entries: readonly NosmapsRelayEntry[];
  readonly graph: NosmapsGraphState;
  readonly curation: {
    readonly counted: readonly unknown[];
    readonly curators: readonly unknown[];
    readonly manual: readonly unknown[];
  };
  readonly quarantined: readonly unknown[];
  readonly unresolved: readonly unknown[];
  readonly deletions: {readonly accepted: number; readonly rejected: number};
  readonly coverage: {readonly [relay: string]: NosmapsRelayCoverage};
  readonly topics: readonly string[];
  /** Epoch milliseconds, NOT a formatted date. */
  readonly asOf: number;
  readonly diagnostics: readonly string[];
  readonly rounds?: readonly unknown[];
  readonly stats?: NosmapsRequestStats;
}

interface NosmapsLoadCatalogOptions {
  relays?: readonly string[];
  topics?: readonly string[];
  manualCounted?: readonly string[];
  viewerPubkey?: string;
  viewerNpub?: string;
  useNip07?: boolean;
  useCache?: boolean;
  nowMs?: number;
  timeoutMs?: number;
  tier2?: boolean;
}

/** Every validator returns this discriminated shape; the payload key differs per
    kind, so each validator narrows it further. */
type NosmapsValidation<Key extends string, Payload> =
  | {readonly ok: false; readonly reason: string}
  | ({readonly ok: true} & {readonly [K in Key]: Payload});

interface NosmapsSoftwareRecord {
  readonly coordinate: string;
  readonly publisher: string;
  readonly d: string;
  readonly state: 'active' | 'withdrawn';
  readonly name: string;
  readonly summary: string;
  readonly homepage: string | null;
  readonly supersededBy: string | null;
  readonly topics: readonly string[];
  readonly eventId: string | null;
  readonly createdAt: number;
}

interface NosmapsCurationSet {
  readonly members: readonly string[];
  readonly ignoredMembers: readonly string[];
  readonly title: string | null;
  readonly image: string | null;
  readonly description: string | null;
  readonly eventId: string | null;
  readonly createdAt: number;
}

interface NosmapsFollowList {
  readonly pubkey: string;
  readonly follows: readonly string[];
  readonly malformed: number;
  readonly total: number;
  readonly eventId: string | null;
  readonly createdAt: number;
}

interface NosmapsDeletionRequest {
  readonly author: string;
  readonly ids: readonly string[];
  readonly addresses: readonly string[];
  readonly eventId: string | null;
  readonly createdAt: number;
}

interface NosmapsDeletionIndex {
  readonly ids: {readonly [eventId: string]: readonly string[]};
  readonly addresses: {readonly [coordinate: string]: number};
  readonly accepted: number;
  readonly rejected: number;
}

/** A Nostr event as it arrives from a relay. Only the fields this module reads
    are named; `id`/`sig` are absent on the plain fixtures the tests build. */
interface NosmapsNostrEvent {
  readonly id?: string;
  readonly sig?: string;
  readonly pubkey: string;
  readonly kind: number;
  readonly tags: readonly (readonly string[])[];
  readonly content: string;
  readonly created_at: number;
}

/** A record that lost to a newer one but was quarantined rather than dropped. */
interface NosmapsQuarantined {
  readonly coordinate: string;
  readonly eventId: string | null;
  readonly pubkey: string | null;
  readonly createdAt: number | null;
  readonly reason: string;
}

interface NosmapsWinner {
  readonly coordinate: string;
  readonly record: NosmapsSoftwareRecord;
  readonly event: NosmapsNostrEvent;
  /** A newer record that was quarantined; surfaced, never silently dropped. */
  readonly quarantinedNewer: {
    readonly eventId: string | null;
    readonly reason: string;
    readonly createdAt: number;
  } | null;
  readonly observedVersions: number;
}

interface NosmapsWinnerSelection {
  readonly winners: readonly NosmapsWinner[];
  readonly quarantined: readonly NosmapsQuarantined[];
}

/** §6.2 tier-1 follow graph. `state` is 'none' when no viewer key resolved. */
interface NosmapsDerivedGraph {
  readonly viewerPubkey: string | null;
  readonly state: string;
  readonly pubkeys: readonly string[];
  readonly coverage: string;
  readonly followsUsed: number;
  readonly followsTotal: number;
  readonly malformedPTags: number;
  readonly truncated: boolean;
  readonly followListId?: string | null;
  readonly followListCreatedAt?: number | null;
}

interface NosmapsCurator {
  readonly curator: string;
  readonly setsObserved: number;
  readonly setsUsed: number;
  readonly truncated: boolean;
  readonly setIds: readonly string[];
  readonly memberCount: number;
}

interface NosmapsCurationMembership {
  readonly counted: readonly string[];
  readonly curators: readonly NosmapsCurator[];
  /** coordinate -> the curators who recommend it. */
  readonly recommenders: {readonly [coordinate: string]: readonly string[]};
  readonly learned: readonly string[];
}

/** §9.4 byte-aware chunking. `ok: false` carries a reason and no chunks. */
interface NosmapsChunkResult {
  readonly ok: boolean;
  readonly reason?: string;
  readonly chunks: readonly (readonly unknown[])[];
  readonly filterCount?: number;
}

/** A NIP-01 REQ filter. The named fields are the ones this module reads; the
    index signature carries the '#<tag>' keys, whose values it never inspects. */
interface NosmapsRelayFilter {
  readonly kinds?: readonly number[];
  readonly authors?: readonly string[];
  readonly ids?: readonly string[];
  readonly since?: number;
  readonly until?: number;
  readonly limit?: number;
  readonly search?: string;
  readonly [tagFilter: string]: unknown;
}

interface NosmapsCatalogCache {
  open(): Promise<unknown>;
  putRecord(record: unknown): Promise<unknown>;
  getRecord(coordinate: string): Promise<unknown>;
  getAll(): Promise<readonly unknown[]>;
  wipe(): Promise<unknown>;
  deleteDatabase(): Promise<unknown>;
  isFresh(record: unknown, nowMs?: number): boolean;
}

interface NosmapsCatalog {
  readonly POLICY: NosmapsCatalogPolicy;
  readonly SOFTWARE_SCHEMA: string;
  readonly SOFTWARE_D_PREFIX: string;
  validateSoftwareEvent(event: unknown, opts?: unknown): NosmapsValidation<'record', NosmapsSoftwareRecord>;
  validateCurationSetEvent(event: unknown, opts?: unknown): NosmapsValidation<'set', NosmapsCurationSet>;
  validateFollowListEvent(event: unknown, opts?: unknown): NosmapsValidation<'followList', NosmapsFollowList>;
  validateDeletionEvent(event: unknown, opts?: unknown): NosmapsValidation<'deletion', NosmapsDeletionRequest>;
  collectDeletions(events: readonly unknown[], opts?: unknown): NosmapsDeletionIndex;
  /** The highest (created_at, id) event of the group, or null for an empty one. */
  selectAddressableWinner(events: readonly unknown[]): NosmapsNostrEvent | null;
  selectSoftwareWinners(events: readonly unknown[], opts?: unknown): NosmapsWinnerSelection;
  deriveGraph(opts?: unknown): NosmapsDerivedGraph;
  curationMembership(opts?: unknown): NosmapsCurationMembership;
  orderEntries<T>(entries: readonly T[], graphState?: unknown): T[];
  buildCatalog(input: unknown): NosmapsCatalogResult;
  chunkFilters(filters: readonly unknown[], opts?: unknown): NosmapsChunkResult;
  /** One filter per author, each carrying that author's `#d` values. */
  groupByAuthor(coordinates: readonly string[]): readonly NosmapsRelayFilter[];
  loadCatalog(opts?: NosmapsLoadCatalogOptions): Promise<NosmapsCatalogResult>;
  /** Hex in, hex out; null for anything that is not a well-formed npub or
      64-char lowercase hex key. */
  decodeNpub(value: unknown): string | null;
  /** Non-strings are rejected with null rather than throwing, so the parameter
      is deliberately `unknown` — nip07-signin.spec.js asserts encodeNpub(null). */
  encodeNpub(pubkeyHex: unknown): string | null;
  isValidCoordinate(coord: unknown): boolean;
  compareCodePoints(a: string, b: string): number;
  readonly cache: NosmapsCatalogCache;
  readonly stats: NosmapsRequestStats;
}

/* ------------------------------------------------------------------------ */
/* The globals themselves                                                    */
/* ------------------------------------------------------------------------ */

interface Window {
  NOSMAPS_DATA: NosmapsData;
  NOSMAPS_I18N: NosmapsI18n;
  NOSMAPS_ICONS: NosmapsIcons;
  NOSMAPS_CATALOG: NosmapsCatalog;
  NOSMAPS_CANONICAL: NosmapsCanonical;
  /* Test hooks published by nip-explorer.js (§ relay render tests). */
  __NOSMAPS_RELAY_RESULT__: NosmapsCatalogResult | null;
  __NOSMAPS_RELAY_LOAD__: (override?: unknown) => Promise<NosmapsCatalogResult | null>;
  __NOSMAPS_SET_STATE__: (next: string) => void;
}
