const { test, expect } = require('@playwright/test');
const base = process.env.NOSMAPS_BASE_URL || 'http://127.0.0.1:4173';
function collectErrors(page){const errors=[];page.on('console',m=>{if(m.type()==='error')errors.push(`console: ${m.text()}`)});page.on('pageerror',e=>errors.push(`pageerror: ${e.message}`));return errors;}

test('A/B/C regression and updated D entry', async({page})=>{const errors=collectErrors(page);await page.goto(`${base}/index.html`);for(const mode of ['A','B','C']){await expect(page.getByRole('button',{name:`${mode}案を操作する`})).toBeVisible();}await expect(page.getByRole('heading',{name:'機能探索・比較（NIP裏付け）'})).toBeVisible();for(const mode of ['A','B','C']){await page.getByRole('button',{name:`${mode}案を操作する`}).click();await expect(page.locator('.tool-card').first()).toBeVisible();await page.locator('.tool-card .secondary').first().click();await expect(page.locator('#detail-dialog')).toBeVisible();await page.keyboard.press('Escape');await page.goto(`${base}/index.html`);}expect(errors).toEqual([]);});

test('feature selection reverse lookup and dead opt-in',async({page})=>{const errors=collectErrors(page);await page.goto(`${base}/nip-explorer.html`);await page.getByRole('searchbox',{name:'機能名・利用場面・代替したいこと'}).fill('zapを送りたい');await page.getByRole('option',{name:/Wallet・Zap/}).click();await expect(page.locator('#selected-feature-summary')).toContainText('Wallet・Zap');await expect(page.locator('.feature-tool-card')).toHaveCount(await page.locator('.feature-tool-card').count());expect(await page.locator('.feature-tool-card').count()).toBeGreaterThan(0);await expect(page.locator('.feature-tool-card.dead-tool')).toHaveCount(0);await page.getByLabel('終了／到達不能も含める').check();expect(await page.locator('.feature-tool-card.dead-tool').count()).toBeGreaterThan(0);await expect(page.getByRole('button',{name:'同じ機能の稼働候補へ戻る'}).first()).toBeVisible();expect(errors).toEqual([]);});

test('OSS mock source and evidence/NIP basis',async({page})=>{const errors=collectErrors(page);await page.goto(`${base}/nip-explorer.html`);const source=page.getByRole('button',{name:/架空ソース/}).first();await expect(source).toBeVisible();await source.click();await expect(page.getByRole('heading',{name:/架空ソース/})).toBeVisible();await expect(page.locator('#evidence-content')).toContainText('実在リポジトリへは移動しません');await page.getByRole('button',{name:'閉じる'}).click();await page.getByRole('button',{name:'機能の根拠詳細'}).first().click();await expect(page.locator('#evidence-content')).toContainText('NIP-');await page.locator('.basis-row').first().click();await expect(page.locator('#evidence-content')).toContainText('モック観測主体');await expect(page.locator('#evidence-content')).toContainText('公式NIP一次資料');expect(errors).toEqual([]);});

test('maximum three feature matrix with metadata',async({page})=>{const errors=collectErrors(page);await page.goto(`${base}/nip-explorer.html`);const boxes=page.locator('[data-compare-tool]');expect(await boxes.count()).toBeGreaterThanOrEqual(4);await boxes.nth(0).check();await boxes.nth(1).check();await boxes.nth(2).check();await boxes.nth(3).click();await expect(page.locator('#compare-summary')).toContainText('3件');await page.getByRole('button',{name:'機能で比較'}).click();await expect(page.getByRole('heading',{name:'3件の機能比較'})).toBeVisible();await expect(page.locator('.feature-matrix thead th')).toHaveCount(4);for(const label of ['投稿・返信','OS','カテゴリ','更新状態','提供形態','OSS','最終観測'])await expect(page.locator('.feature-matrix')).toContainText(label);await page.getByRole('button',{name:'NIP裏付け'}).first().click();await expect(page.locator('#evidence-dialog')).toBeVisible();expect(errors).toEqual([]);});

test('state lab loading empty error partial offline',async({page})=>{const errors=collectErrors(page);await page.goto(`${base}/nip-explorer.html`);const expected={loading:'読み込み中',empty:'0件',error:'取得できません',partial:'partial'};for(const name of ['loading','empty','error','partial','offline']){await page.getByRole('button',{name,exact:true}).click();if(name==='offline')await expect(page.locator('#offline-banner')).toBeVisible();else await expect(page.locator('#ui-state-view')).toContainText(new RegExp(expected[name],'i'));}expect(errors).toEqual([]);});

test.describe('mobile 375px',()=>{test.use({viewport:{width:375,height:812}});test('no overflow, compact first view and collapsed filters',async({page})=>{const errors=collectErrors(page);await page.goto(`${base}/nip-explorer.html`);await expect(page.locator('#filter-details')).not.toHaveAttribute('open','');await expect(page.locator('#feature-query')).toBeVisible();await expect(page.locator('.feature-chip').first()).toBeVisible();const metrics=await page.evaluate(()=>{const q=document.querySelector('#feature-query').getBoundingClientRect();const preview=document.querySelector('#feature-preview').getBoundingClientRect();return {scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth,queryTop:q.top,previewBottom:preview.bottom,heroBottom:document.querySelector('.feature-hero').getBoundingClientRect().bottom}});expect(metrics.scroll).toBeLessThanOrEqual(metrics.client);expect(metrics.queryTop).toBeLessThan(520);expect(metrics.previewBottom).toBeLessThan(900);await page.locator('#filter-details summary').click();await page.locator('#platform-filter').selectOption('Web');await expect(page.locator('#condition-summary')).toContainText('Web');const after=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth}));expect(after.scroll).toBeLessThanOrEqual(after.client);expect(errors).toEqual([]);});});
